#!/usr/bin/env python3
"""Generate C++ HashTestCase array from a UID list file.

Input format (uids.txt): one UID per line, bytes as hex separated by ':'
  - 16-byte UIDs are used as-is
  - 12-byte UIDs get 0xFF, 0x1C, 0x00, 0xF5 appended
"""

import os
import sys

import murmur_hash3
from hash_uid import hash_uid

SUFFIX_12_BYTE = [0xFF, 0x1C, 0x00, 0xF5]
EXPECTED_LEN = 16


def parse_uid_line(line: str) -> list[int]:
    parts = line.strip().split(':')
    return [int(b, 16) for b in parts if b]


def format_bytes(byte_list: list[int]) -> str:
    return ', '.join(f'0x{b:02X}' for b in byte_list)

def format_bytes_lower_case(byte_list: list[int]) -> str:
    return ', '.join(f'0x{b:02x}' for b in byte_list)

def generate_testcases(input_path: str, output_path: str) -> None:
    with open(input_path, 'r') as f:
        lines = [l for l in f if l.strip()]

    with open(output_path, 'w') as out:
        out.write('// Generated by uid_testcase_generator.py\n')
        out.write('// Don\'t edit this file manually!\n\n')
        out.write('/*\n * Test cases for hashing functions\n */\n\n')
        out.write('#ifndef SBLIB_EIB_TEST_HASHING_TESTCASES\n')
        out.write('#define SBLIB_EIB_TEST_HASHING_TESTCASES\n\n')
        out.write('#include <cstdint>\n\n\n')
        out.write('struct HashTestCase {\n')
        out.write('    uint32_t id;\n')
        out.write('    uint8_t uid[16];\n')
        out.write('    uint8_t serial[6];\n')
        out.write('    uint8_t murMurHash3_x86_32[4];\n')
        out.write('};\n\n')
        out.write('inline HashTestCase testCases[] = {\n')

        record_id = 0
        for line in lines:
            uid = parse_uid_line(line)
            if len(uid) == 12:
                uid += SUFFIX_12_BYTE
            if len(uid) != EXPECTED_LEN:
                print(f'Warning: unexpected UID length {len(uid)}, skipping: {line.strip()}', file=sys.stderr)
                continue

            hash_val = hash_uid(bytes(uid), 6)
            murmur_hash3_val = murmur_hash3.murmur_hash3_x86_32(bytes(uid), seed=0)
            out.write(f'    {{ {record_id}, '
                      f'{{ {format_bytes(uid)} }}, '
                      f'{{ {format_bytes(hash_val)} }}, '
                      f'{{ {format_bytes_lower_case(reversed(murmur_hash3_val))} }} '
                      f'}},\n')
            record_id += 1
        out.write('};\n\n')
        out.write('#endif // SBLIB_EIB_TEST_HASHING_TESTCASES\n\n')

    print(f'Written {len(lines)} test cases to: {output_path}')


if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_file = os.path.join(script_dir, 'uids.txt')
    output_file = os.path.join(script_dir, 'test_hashing_testcases.h')
    generate_testcases(input_file, output_file)
