/**************************************************************************//**
 * @addtogroup SBLIB_BOOTLOADER Selfbus Bootloader
 * @defgroup SBLIB_INTEL_HEX Intel(R) hex file format
 * @ingroup SBLIB_BOOTLOADER
 * @brief   Stream a Buffer to serial port in Intel(R) hex file format
 * @details 
 *
 * @{
 *
 * @file   intelhex.h
 * @author Darthyson <darth@maptrack.de> Copyright (c) 2026
 ******************************************************************************/

/*
 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License version 3 as
 published by the Free Software Foundation.
 ---------------------------------------------------------------------------*/

#ifndef SB_BOOTLOADER_INTELHEX_H_
#define SB_BOOTLOADER_INTELHEX_H_

#include <sblib/serial.h>


#define HEX_DEFAULT_BYTES_PER_LINE (16) //!< default byte number per line in resulting hex stream

/**
 * Sends the data to the serial port in Intel(R) hex file format
 *
 * @param serialPort    The Serial port object to dump the hex content to
 * @param data          Data to dump in Intel(R) hex format to the serial port
 * @param count         Number of bytes to dump
 * @param bytesPerLine  Number of bytes on one line (default is 16, like generated by MCUxpresso)
 * @note The only supported HEX "commands" are data record, start segment record, and end of file
 */
void dumpToSerialinIntelHex(Serial* serialPort, unsigned char* data, unsigned int count, unsigned int bytesPerLine = HEX_DEFAULT_BYTES_PER_LINE);


#endif /* SB_BOOTLOADER_INTELHEX_H_ */

/** @}*/
